### ISSUE TITLE
remove unused packages from pubspec.yaml

### ISSUE THREAD

**Issue by kmahmood74** [EnsembleUI/ensemble_file_manager#2]
```yaml
  ensemble_ts_interpreter:
    git:
      url: https://github.com/EnsembleUI/ensemble_ts_interpreter.git
      ref: master
```
should not be in pubspec.yaml as you don't use it
